version: "3"

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - 5432:5432
  pgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    environment:
      PHP_PG_ADMIN_SERVER_HOST: database
      PHP_PG_ADMIN_SERVER_PORT: 5432
    ports:
      - 8080:80
  redis:
    image: redis:5-alpine
    ports: [6379]
